#!/usr/bin/env python3
"""Render each project's initScripts block from the mopay repo's own migrations.

The schema belongs to the application, not to the platform: managed-postgres is generic and
carries none of it. Each developer Resource supplies its own through
`parameters.initScripts`, and this generates those blocks so the repo's db/migrations stay
the single source of truth rather than being copied by hand.

    ./scripts/render-init-scripts.py [path-to-demo-usecase] [-o OUTDIR]

Output is a YAML fragment per database, ready to paste into (or be read by) the Resource
manifests authored in the developer step. Re-run after any migration change.

Replaces render-resource-types.py, which inlined the same SQL into two per-application
ClusterResourceTypes — the arrangement that made onboarding a third application a platform
change.
"""
import argparse
import os
import sys

import yaml

# (Resource name, project, subdir under the repo, filename prefix)
DATABASES = [
    ("mopay-db", "mopay", "", "mopay"),
    ("merchant-db", "merchant-platform", "merchant-api", "merchant"),
]

# Per-environment values the scripts need as psql variables. managed-postgres injects each
# key K as OCINIT_K and offers it to psql as -v k=<value>; the type never interprets them.
INIT_ENV = {
    "mopay-db": {
        "REGION": "<KE or NG — per environment>",
        "HOUSE_ID": "mopay_house",
    },
    "merchant-db": {},
}


class Dumper(yaml.SafeDumper):
    def ignore_aliases(self, data):
        return True


def _str(dumper, data):
    return dumper.represent_scalar("tag:yaml.org,2002:str", data,
                                   style="|" if "\n" in data else None)


Dumper.add_representer(str, _str)


def migrations(repo, subdir, prefix):
    """The repo's *.sql, renamed *.psql so initdb skips them.

    initdb executes *.sql itself and cannot bind psql variables; these migrations need
    :app_role, :app_password and (for mopay) :region and :house_id. The unrecognised
    extension defers them to the type's 99-migrate.sh, which can bind all of those.
    """
    d = os.path.join(repo, subdir, "db", "migrations")
    if not os.path.isdir(d):
        sys.exit(f"no migrations directory at {d}")
    return {
        f"{prefix}-{n[:-4].replace('_', '-')}.psql": open(os.path.join(d, n)).read()
        for n in sorted(os.listdir(d)) if n.endswith(".sql")
    }


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("repo", nargs="?", default=os.environ.get(
        "MOPAY_REPO",
        os.path.join(os.path.dirname(__file__), "..", "..",
                     "2026-NBO-Internal-Developer-Platform-tutorial-2", "demo-usecase")))
    ap.add_argument("-o", "--outdir", default=os.path.join(os.path.dirname(__file__), "..", "generated"))
    a = ap.parse_args()

    os.makedirs(a.outdir, exist_ok=True)
    for name, project, subdir, prefix in DATABASES:
        scripts = migrations(a.repo, subdir, prefix)
        doc = {
            "parameters": {"database": name.replace("-db", ""), "initScripts": scripts},
            "environmentConfigs": {"initEnv": INIT_ENV[name]},
        }
        path = os.path.join(a.outdir, f"{name}.initScripts.yaml")
        with open(path, "w") as f:
            f.write(f"# GENERATED by scripts/render-init-scripts.py — do not edit by hand.\n"
                    f"# Fragment for the `{name}` Resource in project `{project}`.\n"
                    f"# Regenerate after any change to {os.path.join(subdir, 'db/migrations') or 'db/migrations'}.\n")
            yaml.dump(doc, f, Dumper=Dumper, default_flow_style=False, sort_keys=False, width=100)
        print(f"wrote {os.path.relpath(path)}  ({len(scripts)} scripts, {sum(map(len, scripts.values()))} bytes of SQL)")


if __name__ == "__main__":
    main()
